# Generated by Django 5.0.4 on 2025-03-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_returnorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recomended',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
