# Generated by Django 5.0.4 on 2025-03-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_product_recomended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='recomended',
            new_name='category',
        ),
    ]
