# Generated by Django 5.0.4 on 2025-04-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_raiting',
            field=models.FloatField(default=0.0),
        ),
    ]
